### ISSUE TITLE
Error "value of 'count' cannot be computed"

### ISSUE THREAD

**Issue by xliiv** [terraform-aws-modules/terraform-aws-notify-slack#10]
So I'm mostly copied the code from [cloudwatch-alerts-to-slack](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/tree/master/examples/cloudwatch-alerts-to-slack) example.
And I'm getting error:

```
Error: Error refreshing state: 1 error(s) occurred:

* module.notify_slack.data.aws_iam_policy_document.lambda: data.aws_iam_policy_document.lambda: value of 'count' cannot be computed
```

Here's the copied code:

```
resource "aws_kms_key" "this" {
  description = "KMS key for notify-slack test"
}

resource "aws_kms_alias" "this" {
  name          = "alias/kms-test-key"
  target_key_id = "${aws_kms_key.this.id}"
}

data "aws_kms_ciphertext" "slack_url" {
  # i'm aware this is wrong :)
  plaintext = "https://hooks.slack.com/services/AAA/BBB/CCC"
  # or?
  # key_id    = "${aws_kms_key.this.key_id}"
  key_id    = "${aws_kms_key.this.arn}"
}

module "notify_slack" {
  source = "terraform-aws-modules/notify-slack/aws"
  version = "1.3.0"

  sns_topic_name = "slack-topic"

  slack_webhook_url = "${data.aws_kms_ciphertext.slack_url.ciphertext_blob}"
  slack_channel     = "aws-notification"
  slack_username    = "reporter"

  kms_key_arn = "${aws_kms_key.this.arn}"
}

resource "aws_cloudwatch_metric_alarm" "LambdaDuration" {
  alarm_name          = "NotifySlackDuration"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "1"
  metric_name         = "Duration"
  namespace           = "AWS/Lambda"
  period              = "60"
  statistic           = "Average"
  threshold           = "5000"
  alarm_description   = "Duration of notifying slack exceeds threshold"

  alarm_actions = ["${module.notify_slack.this_slack_topic_arn}"]

  dimensions {
    FunctionName = "${module.notify_slack.notify_slack_lambda_function_name}"
  }
}
```
Am I missing something?

**Comment by xliiv** [comment]
It's something with `Option 3` setup:
```
resource "aws_kms_key" "this" {
  description = "KMS key for notify-slack test"
}

resource "aws_kms_alias" "this" {
  name          = "alias/kms-test-key"
  target_key_id = "${aws_kms_key.this.id}"
}

// kms_key_arn = "${aws_kms_key.this.arn}"
```
becasue `Option 1` works:

```
variable "kms_key_arn" {
  default = "arn:aws:kms:eu-west-1:835367859851:key/054b4846-95fe-4537-94f2-1dfd255238cf"
}

// kms_key_arn = "${var.kms_key_arn}"
```

**Comment by xliiv** [comment]
The problem is with this line:
https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/efac652a08a1a8f9ccb99dc660dc0cda47d36f25/iam.tf#L31
because when I fix the count to 0 or 1 (and use this module as sources) like
```
data "aws_iam_policy_document" "lambda" {
  #count = "${var.kms_key_arn == "" ? 0 : 1}"
  count = 1 # or 0
  source_json = "${data.aws_iam_policy_document.lambda_basic.json}"

  statement {
..
```
Everything works

Related issue: https://github.com/hashicorp/terraform/issues/17421

**Comment by antonbabenko** [comment]
@xliiv sorry for the delay in my response.

Yes, HCL2 will have it fixed. Meanwhile, you have to specify key using any of available options (static var, data-source, or pass from tfvars, or from CLI). Everything will work except computed values (`${aws_kms_key.this.arn}`).

There is not much this module can do about it to keep in an easy-maintainable condition.

**Comment by xliiv** [comment]
Is this mean that [example](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/tree/master/examples/cloudwatch-alerts-to-slack#option-1) doesn't work?
There is used `${aws_kms_key.this.arn}`.

**Comment by antonbabenko** [comment]
You are right, it does not work as it is now in that example. My bad.

I will make a PR now which will fix this.

**Comment by antonbabenko** [comment]
[v1.9.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v1.9.0) has been released. I've updated examples there.

Thanks a lot for opening this issue!
