### ISSUE TITLE
v4.0.0 allows Terraform 0.12 but uses 'depends_on' on module block

### ISSUE THREAD

**Issue by anarsen** [terraform-aws-modules/terraform-aws-notify-slack#100]
See https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/793b6be5c1c711593d53b64bf5f8f66bb1e762b0/main.tf#L118

**Comment by antonbabenko** [comment]
Hi, Anders!

Please check this comment - https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/97#issuecomment-673651796

v4.0 - is for Terraform 0.13 users, but v3.4.0 - is for Terraform 0.12.

**Comment by anarsen** [comment]
But shouldn't the `required_version` reflect that then?

https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/793b6be5c1c711593d53b64bf5f8f66bb1e762b0/versions.tf#L2

**Comment by antonbabenko** [comment]
Yes, it should, I will update it now.

**Comment by antonbabenko** [comment]
Fixed in #100, and [v4.1.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v4.1.0) has been just released.
