### ISSUE TITLE
Any way to upgrade lambda module version to relax the AWS provider version requirement for TF 0.12?

### ISSUE THREAD

**Issue by anarsen** [terraform-aws-modules/terraform-aws-notify-slack#102]
_**Note** This issue might belong in terraform-aws-modules/terraform-aws-lambda - sorry if that's the case_

## Context

The latest version for TF 0.12 as of this writing is v3.4.0, and relies on https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/v1.6.0.

Unfortunately, `terraform-aws-modules/terraform-aws-lambda`  v1.6.0 has a pretty strict version requirement on the `aws` provider:

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/aea2b6da21bcde99ed5fdd0ccc27378b84eeda25/versions.tf#L5

## Question

What are your thoughts on creating a Terraform 0.12-compatible version of `terraform-aws-modules/terraform-aws-lambda` with a more relaxed AWS provider version pin such as `aws = ">= 2.46"`.

**Comment by antonbabenko** [comment]
Good point. I think we can have Lambda module version 1.6.0 updated to have support for AWS provider version 3, which is going to be used just by this notify-slack module.

**Comment by antonbabenko** [comment]
[v3.5.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v3.5.0) has been just released with this improvement.

**Comment by anarsen** [comment]
Thanks for the swift response, @antonbabenko. It works as expected.
