### ISSUE TITLE
Upgrading to 0.13

### ISSUE THREAD

**Issue by rohitjha941** [terraform-aws-modules/terraform-aws-notify-slack#103]
I am trying to upgrade to terraform 0.13, I have updated the version. I am facing this err when running plan 

```
To work with
module.infra.module.slack_notification.module.cloudwatch_event_notification.data.archive_file.notify_slack[0]
its original provider configuration at
provider["registry.terraform.io/-/archive"] is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.infra.module.slack_notification.module.cloudwatch_event_notification.data.archive_file.notify_slack[0],
after which you can remove the provider configuration again.
```

Thanks

**Comment by antonbabenko** [comment]
Hi @rohitjha941 !

I think you can get this problem solved by running `terraform 0.13upgrade` and read "Explicit Provider Source Locations" section in [upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations). It covers this case in detail.

I am pretty sure there is nothing we can do about the issue in this module, so closing this issue.

**Comment by crosbymichael1** [comment]
@rohitjha941 Were you able to work through this problem and if so how did you fix it?

**Comment by ZilvinasKucinskas** [comment]
Did someone solve this? I am unable to find a solution to upgrade right now. Terraform 0.13 is compatible only with v4 of `terraform-aws-modules/notify-slack/aws` and `v4` likely changes the resources 🤔
