### ISSUE TITLE
terraform-provider-aws v3.0.0 breaks aws_cloudwatch_log_group output

### ISSUE THREAD

**Issue by ecktom** [terraform-aws-modules/terraform-aws-notify-slack#105]
When upgrading to v3.0.0 of terraform-provider-aws I get the following diff which looks like a breaking change:

```
  ~ resource "aws_iam_policy" "additional_json" {
        arn    = "arn:aws:iam::XXXX:policy/notify_slack"
        id     = "arn:aws:iam::XXXX:policy/notify_slack"
        name   = "notify_slack"
        path   = "/"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                        Action   = [
                            "logs:PutLogEvents",
                            "logs:CreateLogStream",
                        ]
                        Effect   = "Allow"
                      ~ Resource = "arn:aws:logs:eu-central-1:XXXX:log-group:/aws/lambda/notify_slack:*" -> "arn:aws:logs:eu-central-1:XXXX:log-group:/aws/lambda/notify_slack"
                        Sid      = "AllowWriteToCloudwatchLogs"
                    },
                ]
                Version   = "2012-10-17"
            }
        )
    }
```

Please see:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_cloudwatch_log_group

Similar Issues:
https://github.com/nozaq/terraform-aws-secure-baseline/issues/118

**Comment by ecktom** [comment]
@antonbabenko can you confirm this error?

**Comment by antonbabenko** [comment]
I will take a look at this issue later this week.

**Comment by antonbabenko** [comment]
Thanks for the report. I missed this in the [upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade).

[v4.2.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v4.2.0) has been just released.
