### ISSUE TITLE
[enhancement] Use name_prefix for cloudwatch log group to avoid namespace collisions

### ISSUE THREAD

**Issue by sblack4** [terraform-aws-modules/terraform-aws-notify-slack#111]
https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/82f536b8299df9a6f186e946fb2b51b5f34cc4af/main.tf#L52

We already have another similarly named group and so I get this error.

```
Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/lambda/notify_slack' already exists.
```

This can be avoided by using a `name_prefix`, https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#name_prefix

**Comment by bryantbiggs** [comment]
duplicate #104
