### ISSUE TITLE
Please update terraform-aws-lambda module version to 1.28.0 to allow the use of provider Random 3.0

### ISSUE THREAD

**Issue by jecnua** [terraform-aws-modules/terraform-aws-notify-slack#118]
Hi all,

Connected to:

- https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/70

The new version 1.28.0 has just been released.

- https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.28.0

Updating this dependency will allow us to use Random provider v3.0.

**Comment by antonbabenko** [comment]
Fixed.

[v4.7.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v4.7.0) has been just released.
