### ISSUE TITLE
Formatting Issue after v4.11.0 

### ISSUE THREAD

**Issue by KaKeimei** [terraform-aws-modules/terraform-aws-notify-slack#129]
I am using codepipeline  notification to get informed about the execution status.

The message aws returned is like this:

![image](https://user-images.githubusercontent.com/41569443/109126943-33536a00-7791-11eb-9883-ab5b05b4d89a.png)

But in the slack channel , the message was transformed into this:

![image](https://user-images.githubusercontent.com/41569443/109127071-567e1980-7791-11eb-9aca-c920a204db15.png)

The detail resources are missing.
Looks like array field and object field is missing after formatting.

**Comment by sharq1** [comment]
Is there any chance this gets fixed?

**Comment by antonbabenko** [comment]
Probably this has been fixed in the latest release [v4.17.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/tag/v4.17.0).

Please reopen if the problem still exists.
