### ISSUE TITLE
Module not idempotent

### ISSUE THREAD

**Issue by rgreinho** [terraform-aws-modules/terraform-aws-notify-slack#132]
## Description

The module is not idempotent and causes resources to be recreated with each plan.

## Versions

 - Terraform: Terraform v0.13.6
 - Provider(s): hashicorp/aws v3.20.0
 - Module: terraform-aws-modules/notify-slack/aws 4.12.0

## Reproduction

* Run the plan twice in a row: `terraform plan`

### Code Snippet to Reproduce

```hcl
module "notify_slack" {
  source  = "terraform-aws-modules/notify-slack/aws"
  version = "~> 4.0"

  lambda_function_name = "${var.environment}-${var.region}-lambda-notify-slack"

  slack_webhook_url = var.slack_alerts_webhook
  slack_channel     = var.slack_alerts_channel
  slack_username    = "our-slack-username"

  sns_topic_name = "Slack-Alerts"
```

## Expected behavior

The second time I run the `terraform plan` command, there should not be any new resource created.

## Actual behavior

A resource get recreated every time.

```hcl
 # module.notify_slack.module.lambda.null_resource.archive[0] must be replaced
-/+ resource "null_resource" "archive" {
      ~ id       = "8162547318031137166" -> (known after apply)
      ~ triggers = { # forces replacement
            "filename"  = "builds/e0cb3a6677325caaef83e21b18d31cd83bfb70b2f5a3b45d81368dfa72822a07.zip"
          ~ "timestamp" = "1615392751274272000" -> "1615501960953185000"
        }
    }
```

**Comment by alexfdz** [comment]
Seems related to  terraform-aws-modules/terraform-aws-lambda#105 and with a proposed solution described in the [FAQ section](https://github.com/terraform-aws-modules/terraform-aws-lambda#faq) in the README:

> Q3: null_resource.archive[0] must be replaced

> Answer: This probably mean that zip-archive has been deployed, but is currently absent locally, and it has to be recreated locally. When you run into this issue during CI/CD process (where workspace is clean), you can set environment variable TF_RECREATE_MISSING_LAMBDA_PACKAGE=false and run terraform apply.

**Comment by antonbabenko** [comment]
You are right, @alexfdz !

I am going to close this issue here.
