### ISSUE TITLE
Add formatting of EventBridge events

### ISSUE THREAD

**Issue by keelefi** [terraform-aws-modules/terraform-aws-notify-slack#139]
## Is your request related to a new offering from AWS?

[aws_cloudwatch_event_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule) and [aws_cloudwatch_event_target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target)

## Is your request related to a problem? Please describe.

Formatting of [Amazon EventBridge events](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events.html)

## Describe the solution you'd like.

AWS EventBridge events are formatted rather than just `json`.

## Describe alternatives you've considered.

None.

## Additional context

We are already using `terraform-aws-notify-slack` to send alerts from our AWS setup as nicely formatted slack messages. We have both CloudWatch Alarms and CloudWatch LogMetric Alarms. However, now we would like to have some EventBridge events, too.

**Comment by danielsepulvedab** [comment]
I also wanted to use this module to send EventBridge events to Slack. As @keelefi said the result message is just a JSON. Also I had to manually change the policy for the SNS topic to give `events.amazonaws.com` permission to publish to there. It would be nice if that also gets included here.
I could try to put up a PR if there's interest to merge it here.

**Comment by svenlito** [comment]
@danielsepulvedab please go ahead with your PR! :)

**Comment by antonbabenko** [comment]
@danielsepulvedab @svenlito Can this be closed now since yesterday's release of [4.17.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/tag/v4.17.0)?

**Comment by danielsepulvedab** [comment]
Yes. Thanks for the release!

**Comment by antonbabenko** [comment]
Thank you very much for your code changes, too!

Do not hesitate to review other open issues/prs if you have the possibility and tag my name if you think they are good to be merged.
