### ISSUE TITLE
Consecutive terraform plan always show changes to Lambda function

### ISSUE THREAD

**Issue by jmstone617** [terraform-aws-modules/terraform-aws-notify-slack#161]
## Description

Every time a `terraform plan` is run, the filename of the Lambda function is changing. `"null_resource" "archive"` is different every time, and thus the lambda function is destroyed and recreated on every apply.

I think the issue is related to executing this module twice in the same config. According to the docs for the Lambda module, a collision can occur if you do that and so there's an extra_hash you can add, but I don't see that as an input for this module.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:
v1.1.2
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
 - Module:

## Reproduction

1) Define this module twice in the same config. You will need to override the lambda_function_name otherwise there will be a collision.

No

Yes

1) Apply once successfully
2) Change nothing, immediately run `terraform plan` and see that several resources are proposed to be replaced.

## Expected behavior
I would expect that a successful apply and subsequent `plan` would not have any changes

## Actual behavior
What is actually happening is that 6 resources are being proposed to be added, 5 changed, and 6 destroyed.

### Terminal Output Screenshot(s)

![Screen Shot 2022-01-13 at 8 57 56 PM](https://user-images.githubusercontent.com/1200531/149449317-9d0f7fb8-0359-42cd-98c4-1d641fbf801d.png)

**Comment by antonbabenko** [comment]
> You will need to override the lambda_function_name otherwise there will be a collision.

lambda_function_name should be unique to avoid the behavior you are seeing. I can't imagine a better workaround for this, yet.

Closing this issue.

**Comment by jmstone617** [comment]
`lambda_function_name` is unique, but the behavior is as I described
