### ISSUE TITLE
[TF Cloud] Constant drift on depending module.lambda.null_resource

### ISSUE THREAD

**Issue by rastakajakwanna** [terraform-aws-modules/terraform-aws-notify-slack#165]
## Versions

 - Terraform:
1.1.7
 - Provider(s):
 ```
├── module.slack-incidents
│   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.61.0
│   └── module.lambda
│       ├── provider[registry.terraform.io/hashicorp/aws] >= 3.61.0
│       ├── provider[registry.terraform.io/hashicorp/external] >= 1.0.0
│       ├── provider[registry.terraform.io/hashicorp/local] >= 1.0.0
│       └── provider[registry.terraform.io/hashicorp/null] >= 2.0.0
```
 - Module: `terraform-aws-modules/notify-slack/aws`
 - `module.lambda` with source `terraform-aws-modules/lambda/aws` causes the drift

## Reproduction

Note: Terraform Cloud workspaces with free (shared runners) are used and the issue is reproducible in every single workspace where the module is used which leads me to a conclusion that it is a standard module behavior.

- Create module code
- Terraform apply
- Terraform plan
- repeat apply and plan and watch recurrent drift

### Code Snippet to Reproduce

Use default example from the module, it is always reproducible
```
module "notify_slack" {
  source  = "terraform-aws-modules/notify-slack/aws"
  version = "~> 4.0"

  sns_topic_name = "slack-topic"

  slack_webhook_url = "https://hooks.slack.com/services/AAA/BBB/CCC"
  slack_channel     = "aws-notification"
  slack_username    = "reporter"
}
```

## Expected behavior

- no drift after repeated plan

## Actual behavior

`module.slack-incidents.module.lambda.null_resource.archive[0]` `timestamp` trigger always causes forced replacement.

### Terminal Output Screenshot(s)

![image](https://user-images.githubusercontent.com/18012883/159273397-5db4116a-82a5-48f7-84d8-45437df275ee.png)
Raw output:
```
{"@level":"info","@message":"module.slack-stx-incidents.module.lambda.null_resource.archive[0]: Plan to replace","@module":"terraform.ui","@timestamp":"2022-03-18T17:47:50.202810Z","change":{"resource":{"addr":"module.slack-stx-incidents.module.lambda.null_resource.archive[0]","module":"module.slack-stx-incidents.module.lambda","resource":"null_resource.archive[0]","implied_provider":"null","resource_type":"null_resource","resource_name":"archive","resource_key":0},"action":"replace","reason":"cannot_update"},"type":"planned_change"}
{"@level":"info","@message":"Plan: 1 to add, 0 to change, 1 to destroy.","@module":"terraform.ui","@timestamp":"2022-03-18T17:47:50.202963Z","changes":{"add":1,"change":0,"remove":1,"operation":"plan"},"type":"change_summary"}
```

**Comment by rastakajakwanna** [comment]
This is still an issue.

**Comment by nikolay** [comment]
Yeah, this is so annoying!

**Comment by jwilson418** [comment]
Still an issue on version 5

**Comment by nikolay** [comment]
@jwilson418 v5 only bumped the AWS provider's version. Now all modules redundantly require v4 of the AWS provider, which is not compatible with v3 regarding S3, for example,

**Comment by rastakajakwanna** [comment]
Still an issue, the latest version also forced us to pin the module version below 5 due to the AWS provider upgrade.

**Comment by snmatsui** [comment]
I also got a similar issue. Local files of null_resource sometimes conficts when use this module multiply.

```
module "notify_slack" {
  source  = "terraform-aws-modules/notify-slack/aws"
  version = "~> 5.1"

  for_each = var.notify-topics
  ...
}
```

Error text
```
Error: local-exec provisioner error
with module.notify_slack["A"].module.lambda.null_resource.archive[0]
on .terraform/modules/notify_slack.lambda/package.tf line 65, in resource "null_resource" "archive":
  provisioner "local-exec" {
Error running command 'builds/f887fda392dc3b00a79375b02b5765bf1780db329b87349b0ce68990a1c48276.plan.json': exit status 1. Output: zip: creating 'builds/f887fda392dc3b00a79375b02b5765bf1780db329b87349b0ce68990a1c48276.zip' archive
zip: adding: notify_slack.py
Traceback (most recent call last):
  File ".terraform/modules/notify_slack.lambda/package.py", line 1389, in <module>
    main()
  File ".terraform/modules/notify_slack.lambda/package.py", line 1385, in main
    exit(args.command(args))
  File ".terraform/modules/notify_slack.lambda/package.py", line 1277, in build_command
    bpm.execute(build_plan, zs, query)
  File ".terraform/modules/notify_slack.lambda/package.py", line 318, in __exit__
    self.close()
  File ".terraform/modules/notify_slack.lambda/package.py", line 308, in close
    os.replace(self._tmp_filename, self.filename)
FileNotFoundError: [Errno 2] No such file or directory: 'builds/f887fda392dc3b00a79375b02b5765bf1780db329b87349b0ce68990a1c48276.zip.tmp' -> 'builds/f887fda392dc3b00a79375b02b5765bf1780db329b87349b0ce68990a1c48276.zip'
```

- terraform version: 1.1.9(TFcloud)

**Comment by vicfergar** [comment]
Still an issue.

**Comment by vicfergar** [comment]
Still an issue

**Comment by rafaelsales** [comment]
Still an issue

```
  # module.shared.module.notify_slack.module.lambda.null_resource.archive[0] must be replaced
+/- resource "null_resource" "archive" {
      ~ id       = "8283681871539281269" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "timestamp" = "1661954191061458200" -> "1661954395960079000"
            # (1 unchanged element hidden)
        }
    }
```

**Comment by antonbabenko** [comment]
I know that this issue is still painful for some users.

I have just tried to run a slightly modified example (`recreate_missing_package = false`) on Terraform Cloud, and it seems to work well:

```hcl
module "notify_slack" {
  source  = "terraform-aws-modules/notify-slack/aws"
  version = "~> 4.0"

  sns_topic_name = "slack-topic"

  slack_webhook_url = "https://hooks.slack.com/services/AAA/BBB/CCC"
  slack_channel     = "aws-notification"
  slack_username    = "reporter"

  # Added this argument not to recreate the missing package once it was created
  recreate_missing_package = false
}
```

Could someone confirm that it works well? If so, we need to update README.

**Comment by rastakajakwanna** [comment]
I confirm this parameter removes the drift in my case. Thanks!

Can you think of any possible side-effects when using this parameter? I would not guess this is something I want to add by default just from its name 😄

**Comment by rafaelsales** [comment]
@antonbabenko this solved the issue! Thank you!!

**Comment by lpossamai** [comment]
> I know that this issue is still painful for some users.
> 
> I have just tried to run a slightly modified example (`recreate_missing_package = false`) on Terraform Cloud, and it seems to work well:
> 
> ```terraform
> module "notify_slack" {
>   source  = "terraform-aws-modules/notify-slack/aws"
>   version = "~> 4.0"
> 
>   sns_topic_name = "slack-topic"
> 
>   slack_webhook_url = "https://hooks.slack.com/services/AAA/BBB/CCC"
>   slack_channel     = "aws-notification"
>   slack_username    = "reporter"
> 
>   # Added this argument not to recreate the missing package once it was created
>   recreate_missing_package = false
> }
> ```
> 
> Could someone confirm that it works well? If so, we need to update README.

I still get this issue with version `5.3` on AWS.

**Comment by antonbabenko** [comment]
@rafaelsales @rastakajakwanna Thanks for confirming that it works!

@lpossamai Could you please share more details about your case? Include code snippet, outputs from terraform apply.
