### ISSUE TITLE
Custom lambda function

### ISSUE THREAD

**Issue by sobi3ch** [terraform-aws-modules/terraform-aws-notify-slack#171]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Cannot use my custom lambda function code.

## Describe the solution you'd like.
Ability to overwrite default `source_path` in module lambda ([source](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/master/main.tf#L81))

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.2.0 :tada:
