### ISSUE TITLE
Add support for pre-built lambda package

### ISSUE THREAD

**Issue by tl-matthew-harrold** [terraform-aws-modules/terraform-aws-notify-slack#174]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
The module doesn't expose any method to supply a pre-packaged lambda.

## Describe the solution you'd like.
I'd like to be able to provide a pre-packaged lambda

## Describe alternatives you've considered.
None

## Additional context
We don't have Python installed in the environment we run Terraform from, and would rather avoid installing it for the sake of a single module. Therefore it would be ideal if we can provide our own pre-built lambda package

**Comment by antonbabenko** [comment]
Good idea, PR is welcome for this feature.
