### ISSUE TITLE
Expose dead_letter_target_arn variable from lambda module

### ISSUE THREAD

**Issue by chris3ware** [terraform-aws-modules/terraform-aws-notify-slack#177]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.

I'm unable to configure a dead-letter queue for the lambda function

## Describe the solution you'd like.

I'd like to be able to pass a dead-letter queue arn into the module. The child module - [terraform-aws-lambda](https://github.com/terraform-aws-modules/terraform-aws-lambda) - support this.

## Additional context

The AWS config [NCSC Cloud Security Principles](https://docs.aws.amazon.com/config/latest/developerguide/operational-best-practices-for-ncsc.html) conformance pack checks for the presence of a dead-letter queue for lambda functions.

**Comment by antonbabenko** [comment]
This should be a relatively simple addition if anyone wants to work on it.

If not, I put it in the priority queue since you are my GitHub Sponsor, and I will make it during the week!

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.4.0 :tada:
