### ISSUE TITLE
putin_khuylo input variable

### ISSUE THREAD

**Issue by richardj-bsquare** [terraform-aws-modules/terraform-aws-notify-slack#191]
## Description

Whilst I agree entirely with the sentiment of this input variable and it's default of true, it was attempting to make the slack channel post fail if set to false by setting the local.create to false. However local.create is not used, and therefore the slack channel will always be created regardless of whether putin is or isn't declared as what has been indicated.

https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/master/variables.tf#L1

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
5.5.0

- Terraform version:
Terraform v1.3.7

- Provider version(s):
n/a

## Expected behavior

Slack channel will not be posted to.

## Actual behavior

Slack channel is posted to.

## Additional context

Make of this 'bug' what you will, and determine whether the inclusion of this input var is intentional, unintentional or silently ignored due to its inherent humour/wisdom.

**Comment by antonbabenko** [comment]
Good catch. PR is welcome.

**Comment by amimas** [comment]
In my experience, the variable also affects deployment of sns topic feedback. If the variable is set to false, all the other stack is deployed except the sns feedback related resources.
