### ISSUE TITLE
Noisy output

### ISSUE THREAD

**Issue by sondrelg** [terraform-aws-modules/terraform-aws-notify-slack#197]
Hi,

Just want to re-open an issue since https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/194 was closed without a response. Seems I cannot reopen that one.

**Comment by sondrelg** [comment]
Please don't close

**Comment by bryantbiggs** [comment]
the build output is to be expected - this is generated by the lambda module. add `build` to your gitignore file - no further action is required here
