### ISSUE TITLE
Support @here in Slack Notifications

### ISSUE THREAD

**Issue by dtrodger** [terraform-aws-modules/terraform-aws-notify-slack#199]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Describe the solution you'd like.
Update [the function that creates the payload for the Slack API call](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/master/functions/notify_slack.py#L316) to include a "link_names": 1 key in the payload if @here is included in the message detail.

**Comment by wstewarttennes** [comment]
@dtrodger agreed! We need this desperately -- could we create a PR for this?

**Comment by antonbabenko** [comment]
@wstewarttennes Yes, please make a PR.

**Comment by wstewarttennes** [comment]
@dtrodger this was closed but did we make a PR for this?
