### ISSUE TITLE
The link to the CloudWatch alarm is no longer valid.

### ISSUE THREAD

**Issue by steve-todorov** [terraform-aws-modules/terraform-aws-notify-slack#203]
## Description

The link to the CloudWatch alarm is no longer valid.

## Versions

```
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.12.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

```
module "notify_slack" {
  source  = "terraform-aws-modules/notify-slack/aws"
  version = "5.6.0"
}
```

## Reproduction Code [Required]

1. Create a CloudWatch metric with an alarm. Make sure the name of the alarm contains `/` such as for example  `ecs/service/upscale` 
2. Connect this alarm to the notify-slack module.
3. Trigger the alarm.

## Actual behavior

The slack report works as expected. However the link to the console is wrong. It will report something like this:

```
Link to Alarm
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarm:alarmFilter=ANY;name=ecs/service/upscale
```

## Expected behavior

The link to the terminal should escape the `/` symbol, because otherwise it won't work. Based on the above example, the right link would be this:
```
Link to Alarm
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarmsV2:alarm/ecs$2Fservice$2Fupscale
```

Or this:
```
Link to Alarm
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarmsV2:alarm/ecs$2Fservice$2Fupscale?~(search~'ecs*2fservice*2fupscale)
```

**Comment by steve-todorov** [comment]
ping

**Comment by lyderichti59** [comment]
I can second that the link is not working well.
Also, when looking at the "message" that cloudwatch alarms are sending to SNS, it seems that the message has a "email" field and that this "email" field's value mentions the below link (which works for me) :
- `https://<region>.console.aws.amazon.com/cloudwatch/deeplink.js?region=<region>#alarmsV2:alarm/<alarmName>`

**Comment by steve-todorov** [comment]
pong.

**Comment by steve-todorov** [comment]
ping.
