### ISSUE TITLE
Apply fails when multiple module calls are used

### ISSUE THREAD

**Issue by joshgch** [terraform-aws-modules/terraform-aws-notify-slack#210]
## Is your request related to a problem? Please describe.
There are some scenarios where we must deploy multiple notify-slack lambdas in a single workspace. We have found that the archive process fails when we have concurrent archival executions happening.

## Describe the solution you'd like.
I believe this is due to zip file corruption with multiple writes to the same file as described in the lambda module here: https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest#a-namebuild-packagea-how-does-building-and-packaging-work

We could work around this if the `hash_extra` var for the lambda module were utilized with unique values for each lambda in this module.

## Describe alternatives you've considered.
N/A

## Additional context
N/A

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.1.0 :tada:
