### ISSUE TITLE
Add formatter for Amazon Managed Prometheus alerts

### ISSUE THREAD

**Issue by jfreeland** [terraform-aws-modules/terraform-aws-notify-slack#226]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

No.

## Describe the solution you'd like.

CAUTION:  I suspect this might not be the right place for this nor the best approach.

I am using this function for sending CloudWatch alarms to Slack.  I wanted to be lazy and piggyback on using the same topic and function to send AMP alarms to Slack.  It technically works as intended, but could potentially be a touch prettier.

## Describe alternatives you've considered.

Using a separate function.

**Comment by antonbabenko** [comment]
Thank you for the request of this important feature. You (or anyone else) are welcome to open pull-requests with such additions. Look into existing formatters for examples.
