### ISSUE TITLE
Lambda version updates not reflected in trigger

### ISSUE THREAD

**Issue by fatmcgav** [terraform-aws-modules/terraform-aws-notify-slack#230]
## Description

When attempting to update the `slack_channel` that a set of notifications target, I observed that the notifications were still being sent to the "old" channel.

Upon reviewing the AWS config, I could see a new version of the lambda had been published. However there was an error on the `triggers` section for the new lambda version as follows:
![Screenshot 2024-08-28 at 09 56 06](https://github.com/user-attachments/assets/2599d11d-c00e-40ee-9d32-b71021b42f42)

After looking at this module code, I believe the issue is here:
https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/2e72539b6719818b973097320e5e7b134c77e453/main.tf#L76

Instead of using the `lambda_function_arn` output, the `lambda_function_qualified_arn`[1] should be used, as that includes the "current" version.

Alternatively, an `alias` could be defined, using the `alias` submodule[2] and that alias is then referenced by the trigger.

[1]: https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/v3.2.0?tab=readme-ov-file#output_lambda_function_qualified_arn
[2] https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/v3.2.0/modules/alias

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `~> 6.0`

- Terraform version: `1.5.7`
- Provider version(s): `5.63.0`

## Reproduction Code [Required]

* Deploy module with `slack_channel` set to `channel-a`
* Test notifications
* Update `slack_channel` value to `channel-b`
* Test notifications

## Expected behavior

Notifications should be sent to `#channel-b`

## Actual behavior

Notification is still sent to `#channel-a`

## Additional context

The current `terraform-aws-modules/lambda/aws` version (`3.2.0`) is _3 years_ old!!!
The latest version is `7.8.1`...

**Comment by fatmcgav** [comment]
I went with option 1 above in #231.

Testing the changes locally and this correctly results in an update to the SNS trigger on a lambda update :D

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.4.1 :tada:
