### ISSUE TITLE
Terraform 0.12

### ISSUE THREAD

**Issue by digitalkaoz** [terraform-aws-modules/terraform-aws-notify-slack#32]
currently Terraform 0.12 is not supported

**Comment by cdaniluk** [comment]
Submitted a new PR For this. Did not find that the PR submitted by @digitalkaoz actually worked. This may also address #21.. tested w/both module ref and local ref in a few different ways and do not think that path swapping is necessary anymore.

**Comment by digitalkaoz** [comment]
@cdaniluk closing in favor of your PR. i didnt tried after upgrade, thanks for your work!
