### ISSUE TITLE
Deprecation Warning occurred with Terraform v0.12.14+

### ISSUE THREAD

**Issue by wittro** [terraform-aws-modules/terraform-aws-notify-slack#49]
Hi, Terraform warns `Quoted references are deprecated` at [this part](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/v2.3.0/main.tf#L107). No need to quote a reference in `depends_on` .

See https://discuss.hashicorp.com/t/terraform-0-12-14-released/3898

**Comment by antonbabenko** [comment]
[v2.5.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v2.5.0) has been just released with this fix.
