### ISSUE TITLE
How can I integrate it with cloudwatch_metric_alarm?

### ISSUE THREAD

**Issue by xliiv** [terraform-aws-modules/terraform-aws-notify-slack#8]
How can I integrated it with
https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html
?
Let's say I'd like to notify slack about idling machines?

**Comment by antonbabenko** [comment]
There is an example for this - https://github.com/terraform-aws-modules/terraform-aws-notify-slack/tree/master/examples/cloudwatch-alerts-to-slack

**Comment by xliiv** [comment]
Thanks, how come I overlooked it? Nvm.
Could we write [here](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/master/examples/cloudwatch-alerts-to-slack/main.tf#L9) where encryption should be?
Now it's written where, so for someone less experienced it's enigmatic. :)

**Comment by antonbabenko** [comment]
You are right, the comment in the code is not perfect. URL can be there and it is fine that it is visible as it is in most cases. That URL will be persisted in stdout and tfstate file anyway.

**Comment by xliiv** [comment]
Thanks for help, I'm closing it.
