### ISSUE TITLE
Invalid Index Error

### ISSUE THREAD

**Issue by asfand-seekasia** [terraform-aws-modules/terraform-aws-notify-slack#80]
I recently ran the build and it caused this. Previously it was working fine. No updates
terraform version: 0.12.12
module version: 2.0

Error: Invalid index

  on .terraform/modules/sns_lambda_slack_notifier/main.tf line 50, in resource "aws_lambda_permission" "sns_notify_slack":
  50:   function_name = aws_lambda_function.notify_slack[0].function_name
    |----------------
    | aws_lambda_function.notify_slack is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on .terraform/modules/sns_lambda_slack_notifier_error/main.tf line 50, in resource "aws_lambda_permission" "sns_notify_slack":
  50:   function_name = aws_lambda_function.notify_slack[0].function_name
    |----------------
    | aws_lambda_function.notify_slack is empty tuple

The given key does not identify an element in this collection value.

**Comment by antonbabenko** [comment]
Please give a try [v3.0.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v3.0.0) which has been just released.

It has a lot of improvements when working with Lambda resources.
