### ISSUE TITLE
Legacy Incoming Webhooks vs. Slack Apps

### ISSUE THREAD

**Issue by klucks83** [terraform-aws-modules/terraform-aws-notify-slack#86]
Slack now appears to have the concept of Legacy Incoming Webhooks (https://api.slack.com/legacy/custom-integrations/incoming-webhooks) and new Incoming Webhooks (or Slack Apps - https://api.slack.com/incoming-webhooks).  

When setting up an incoming webhook the new way (a Slack App), this TF module still works, however the slack_channel, slack_username, and slack_emoji Terraform inputs no longer appear to be needed and/or modifiable via Lambda, as they are a part of the creation process of a Slack App webhook. 

I don't personally have a solution, but wanted to at least bring awareness to this concept and how that may drive future changes to this module. 

```
slack_channel     = "aws-notification"
slack_username    = "reporter"
slack_emoji       = ":thing:"
```

It is also worth noting that the first 2 sentences of this README now link to each of the Webhook creation methods which could be confusing to people setting up a webhook and using this module for the first time. 
- The first sentence links to the new Slack Apps creation process
- The second sentence links to the creation of a legacy Incoming Webhook

**Comment by rahulk94** [comment]
Ideally we should just use the new Slack App webhook configuration so that the webhook avatar and name are respected.
