### ISSUE TITLE
 Make this module runnable with `hashicorp/terraform:light`

### ISSUE THREAD

**Issue by atrakic** [terraform-aws-modules/terraform-aws-notify-slack#87]
This package cannot be used with `hashicorp/terraform:light` - as it requires python runtime. 
Perhaps should be stated in requirements? 
Alternatively simplify lambda handler packaging with data.archive_file.

**Comment by dekimsey** [comment]
Looking at the python code, it's not even clear why a runtime/zip package is even needed. The pip requirements are just for testing, so I'm thinking why bother? The AWS lambda runtime already provides boto3, there isn't anything else the script imports.

**Comment by antonbabenko** [comment]
Data source `archive_file` has a very basic set of features (no excludes, no files mask, etc) and most dangerous is that this data source creates archives during `terraform plan` but I believe `plan` should not create anything meaningful (`terraform apply` should).

Python is needed by the [terraform-aws-lambda](https://github.com/terraform-aws-modules/terraform-aws-lambda) module to build/rebuild a deployment package.

There is already a note in README about [how to make this module work on Terraform Cloud Agents](https://github.com/terraform-aws-modules/terraform-aws-notify-slack#using-with-terraform-cloud-agents) and Python will be a requirement for the foreseen future in the Lambda module (unfortunately for some users, I know).
