### ISSUE TITLE
Failed to execute python3 on Terraform Cloud

### ISSUE THREAD

**Issue by benschwarz** [terraform-aws-modules/terraform-aws-notify-slack#90]
We added this module to a workspace in Terraform Cloud and received the following error:

```
Error: failed to execute "python3": Traceback (most recent call last):
  File ".terraform/modules/notify_slack.lambda/terraform-aws-lambda-1.6.0/package.py", line 6, in <module>
    raise RuntimeError("A python version 3.7 or newer is required")
RuntimeError: A python version 3.7 or newer is required


  on .terraform/modules/notify_slack.lambda/terraform-aws-lambda-1.6.0/package.tf line 3, in data "external" "archive_prepare":
   3: data "external" "archive_prepare" {
```

Looking at the latest commit for `terraform-aws-lambda`, [the Python version is locked at `3.6` rather than 3.7](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/package.py#L5-L6). 

I'm not sure if Terraform Cloud provides a python runtime, or if the Python runtime is required to run the module.

Is this module expected to work when used with Terraform Cloud? Is there a workaround or configuration that should be used for it?

**Comment by ldormoy** [comment]
Same issue with Atlantis, the official docker image doesn't provide a python runtime and I'm very reluctant to install it just for this module.

**Comment by vamshi05** [comment]
I've installed python3 on top of the tfc-agent's image to make it work.

**Comment by benschwarz** [comment]
> I've installed python3 on top of the tfc-agent's image to make it work.

Could you please share the steps you took to achieve this?

**Comment by vamshi05** [comment]
> > I've installed python3 on top of the tfc-agent's image to make it work.
> 
> Could you please share the steps you took to achieve this? @vamshi05

You can build an image with this docker file and use it for your tfc agent. The base image is hashicorp/tfc-agent:latest
`FROM hashicorp/tfc-agent:latest
RUN apt-get -y update && apt-get -y install python3.8 python3-pip
ENTRYPOINT ["/bin/tfc-agent"]`

**Comment by antonbabenko** [comment]
Python 3.8 should be installed on Atlantis, Terraform Cloud Agents, or other systems where you run Terraform.

Could you proofread this note which I am adding into README - https://github.com/terraform-aws-modules/terraform-aws-notify-slack/pull/108/files#diff-04c6e90faac2675aa89e2176d2eec7d8R49-R59 ?

**Comment by benschwarz** [comment]
@antonbabenko I made a suggestion on the commit, otherwise LGTM.

**Comment by antonbabenko** [comment]
[v4.4.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v4.4.0) has been just released with an updated note in README.

Not much else we can do in this module.
