### ISSUE TITLE
Update version requirements to allow AWS provider version 3.0+

### ISSUE THREAD

**Issue by tophercullen** [terraform-aws-modules/terraform-aws-notify-slack#93]
3.0 recently came out but current version restricts it to 2.7. 

The current module version seems to function with 3.0 without modification.

**Comment by paul-pop** [comment]
Unfortunately, the underlying `terraform-aws-modules/lambda` module uses version 1.6.0 so the initialization on Terraform 13 still fails with:

```bash
Error: Unsupported Terraform Core version

  on .terraform/modules/notify_slack.lambda/terraform-aws-lambda-1.6.0/versions.tf line 2, in terraform:
   2:   required_version = "~> 0.12.6"
```

I'm raising a new PR now to upgrade to [1.18.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/CHANGELOG.md#v1180---2020-08-13)
