### ISSUE TITLE
[bug] CloudWatch log group gets created twice and throws an error

### ISSUE THREAD

**Issue by paul-pop** [terraform-aws-modules/terraform-aws-notify-slack#97]
Running the latest [version](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v3.5.0) I noticed a CW log group gets created by both this module and the underlying lambda module, check output:

```
# module.notify_slack.aws_cloudwatch_log_group.lambda[0] will be created
  + resource "aws_cloudwatch_log_group" "lambda" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/lambda/slack-notifications"
      + retention_in_days = 0
    }

# module.notify_slack.module.lambda.aws_cloudwatch_log_group.lambda[0] will be created
  + resource "aws_cloudwatch_log_group" "lambda" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/lambda/slack-notifications"
      + retention_in_days = 0
      + tags              = {
          + "Terraform"    = "true"
        }
    }
```

Then because of this, an error is thrown every time:

```
Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/lambda/slack-notifications' already exists.

  on .terraform/modules/notify_slack.lambda/terraform-aws-lambda-1.18.0/main.tf line 109, in resource "aws_cloudwatch_log_group" "lambda":
 109: resource "aws_cloudwatch_log_group" "lambda" {
```

**Comment by antonbabenko** [comment]
I will take a look at this later today or tomorrow.

**Comment by paul-pop** [comment]
@antonbabenko would #98 be an acceptable fix or did you have something else in mind? 

Initially, I wanted to delegate the entire CloudWatch log creation to the Lambda module but then I saw your comment so decided to the one in this module instead.

```
  # Do not use Lambda's policy for cloudwatch logs, because we have to add a policy
  # for KMS conditionally. This way attach_policy_json is always true independenty of
  # the value of presense of KMS. Famous "computed values in count" bug...
```

**Comment by michaelm-88** [comment]
same error here 
```
Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/lambda/slack_ooh-major' already exists.
  on .terraform/modules/slack_ooh-major.lambda/terraform-aws-lambda-1.18.0/main.tf line 109, in resource "aws_cloudwatch_log_group" "lambda":
 109: resource "aws_cloudwatch_log_group" "lambda" {
```

**Comment by antonbabenko** [comment]
I am looking into this issue now and the solution proposed in #98 is too simple and does not work for several situations.

I propose to have the following:
1. Users of Terraform 0.12 with AWS Provider 3 to use [this module v3.4.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/tree/v3.4.0).
2. Users of Terraform 0.13 can use the latest version of [this module](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/) where Lambda module is the most up-to-date, and `depends_on` which became available in Terraform 0.13 is used for that.

If there are no objections, I will make a new release now.

**Comment by antonbabenko** [comment]
There is [v4.0.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v4.0.0) - for Terraform 0.13 users, and [v3.4.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/tree/v3.4.0) - for Terraform 0.12 users.

Please let me know if there are any issues related to this upgrade.

**Comment by paul-pop** [comment]
That’s much better @antonbabenko thank you. Wasn’t sure on the approach you usually take for managing multiple TF versions.

**Comment by michaelm-88** [comment]
Error: failed to execute "python3": Traceback (most recent call last):
  File ".terraform/modules/slack_ooh-major.lambda/terraform-aws-lambda-1.6.0/package.py", line 6, in <module>
    raise RuntimeError("A python version 3.7 or newer is required")
RuntimeError: A python version 3.7 or newer is required
  on .terraform/modules/slack_ooh-major.lambda/terraform-aws-lambda-1.6.0/package.tf line 3, in data "external" "archive_prepare":
   3: data "external" "archive_prepare" {
[terragrunt] 2020/08/14 10:14:11 Hit multiple errors:
exit status 1
